#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQLNow
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="FSQL")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnCreated();
    partial void InsertCustomer(Customer instance);
    partial void UpdateCustomer(Customer instance);
    partial void DeleteCustomer(Customer instance);
    partial void InsertCustomerDomain(CustomerDomain instance);
    partial void UpdateCustomerDomain(CustomerDomain instance);
    partial void DeleteCustomerDomain(CustomerDomain instance);
    partial void InsertManagedEntityType(ManagedEntityType instance);
    partial void UpdateManagedEntityType(ManagedEntityType instance);
    partial void DeleteManagedEntityType(ManagedEntityType instance);
    partial void InsertProductVersion(ProductVersion instance);
    partial void UpdateProductVersion(ProductVersion instance);
    partial void DeleteProductVersion(ProductVersion instance);
    partial void InsertSQLComputer(SQLComputer instance);
    partial void UpdateSQLComputer(SQLComputer instance);
    partial void DeleteSQLComputer(SQLComputer instance);
    partial void InsertSQLDatabases(SQLDatabases instance);
    partial void UpdateSQLDatabases(SQLDatabases instance);
    partial void DeleteSQLDatabases(SQLDatabases instance);
    partial void InsertSQLInstallType(SQLInstallType instance);
    partial void UpdateSQLInstallType(SQLInstallType instance);
    partial void DeleteSQLInstallType(SQLInstallType instance);
    partial void InsertSQLServer(SQLServer instance);
    partial void UpdateSQLServer(SQLServer instance);
    partial void DeleteSQLServer(SQLServer instance);
    #endregion
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Customer> Customer
		{
			get
			{
				return this.GetTable<Customer>();
			}
		}
		
		public System.Data.Linq.Table<CustomerDomain> CustomerDomain
		{
			get
			{
				return this.GetTable<CustomerDomain>();
			}
		}
		
		public System.Data.Linq.Table<ManagedEntityType> ManagedEntityType
		{
			get
			{
				return this.GetTable<ManagedEntityType>();
			}
		}
		
		public System.Data.Linq.Table<ManagedEntityTypeDBS> ManagedEntityTypeDBS
		{
			get
			{
				return this.GetTable<ManagedEntityTypeDBS>();
			}
		}
		
		public System.Data.Linq.Table<ProductVersion> ProductVersion
		{
			get
			{
				return this.GetTable<ProductVersion>();
			}
		}
		
		public System.Data.Linq.Table<SQLComputer> SQLComputer
		{
			get
			{
				return this.GetTable<SQLComputer>();
			}
		}
		
		public System.Data.Linq.Table<SQLDatabases> SQLDatabases
		{
			get
			{
				return this.GetTable<SQLDatabases>();
			}
		}
		
		public System.Data.Linq.Table<SQLInstallType> SQLInstallType
		{
			get
			{
				return this.GetTable<SQLInstallType>();
			}
		}
		
		public System.Data.Linq.Table<SQLServer> SQLServer
		{
			get
			{
				return this.GetTable<SQLServer>();
			}
		}
		
		public System.Data.Linq.Table<vDatabases> vDatabases
		{
			get
			{
				return this.GetTable<vDatabases>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Customer")]
	public partial class Customer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Name;
		
		private string _NameLong;
		
		private string _Address;
		
		private string _Zip;
		
		private string _City;
		
		private string _Notes;
		
		private System.Nullable<int> _Domains;
		
		private System.Nullable<int> _Computers;
		
		private System.Nullable<int> _Installations;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnNameLongChanging(string value);
    partial void OnNameLongChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnZipChanging(string value);
    partial void OnZipChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnNotesChanging(string value);
    partial void OnNotesChanged();
    partial void OnDomainsChanging(System.Nullable<int> value);
    partial void OnDomainsChanged();
    partial void OnComputersChanging(System.Nullable<int> value);
    partial void OnComputersChanged();
    partial void OnInstallationsChanging(System.Nullable<int> value);
    partial void OnInstallationsChanged();
    #endregion
		
		public Customer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameLong", DbType="NVarChar(120)")]
		public string NameLong
		{
			get
			{
				return this._NameLong;
			}
			set
			{
				if ((this._NameLong != value))
				{
					this.OnNameLongChanging(value);
					this.SendPropertyChanging();
					this._NameLong = value;
					this.SendPropertyChanged("NameLong");
					this.OnNameLongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(120)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Zip", DbType="NVarChar(20)")]
		public string Zip
		{
			get
			{
				return this._Zip;
			}
			set
			{
				if ((this._Zip != value))
				{
					this.OnZipChanging(value);
					this.SendPropertyChanging();
					this._Zip = value;
					this.SendPropertyChanged("Zip");
					this.OnZipChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="NVarChar(120)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="NVarChar(1024)")]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this.OnNotesChanging(value);
					this.SendPropertyChanging();
					this._Notes = value;
					this.SendPropertyChanged("Notes");
					this.OnNotesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Domains", DbType="Int")]
		public System.Nullable<int> Domains
		{
			get
			{
				return this._Domains;
			}
			set
			{
				if ((this._Domains != value))
				{
					this.OnDomainsChanging(value);
					this.SendPropertyChanging();
					this._Domains = value;
					this.SendPropertyChanged("Domains");
					this.OnDomainsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Computers", DbType="Int")]
		public System.Nullable<int> Computers
		{
			get
			{
				return this._Computers;
			}
			set
			{
				if ((this._Computers != value))
				{
					this.OnComputersChanging(value);
					this.SendPropertyChanging();
					this._Computers = value;
					this.SendPropertyChanged("Computers");
					this.OnComputersChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Installations", DbType="Int")]
		public System.Nullable<int> Installations
		{
			get
			{
				return this._Installations;
			}
			set
			{
				if ((this._Installations != value))
				{
					this.OnInstallationsChanging(value);
					this.SendPropertyChanging();
					this._Installations = value;
					this.SendPropertyChanged("Installations");
					this.OnInstallationsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CustomerDomain")]
	public partial class CustomerDomain : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _CustomerName;
		
		private string _DomainDnsName;
		
		private string _JumpServer1;
		
		private string _JumpServer2;
		
		private string _JumpServer3;
		
		private string _JumpServer4;
		
		private string _Notes;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCustomerNameChanging(string value);
    partial void OnCustomerNameChanged();
    partial void OnDomainDnsNameChanging(string value);
    partial void OnDomainDnsNameChanged();
    partial void OnJumpServer1Changing(string value);
    partial void OnJumpServer1Changed();
    partial void OnJumpServer2Changing(string value);
    partial void OnJumpServer2Changed();
    partial void OnJumpServer3Changing(string value);
    partial void OnJumpServer3Changed();
    partial void OnJumpServer4Changing(string value);
    partial void OnJumpServer4Changed();
    partial void OnNotesChanging(string value);
    partial void OnNotesChanged();
    #endregion
		
		public CustomerDomain()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerName", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CustomerName
		{
			get
			{
				return this._CustomerName;
			}
			set
			{
				if ((this._CustomerName != value))
				{
					this.OnCustomerNameChanging(value);
					this.SendPropertyChanging();
					this._CustomerName = value;
					this.SendPropertyChanged("CustomerName");
					this.OnCustomerNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DomainDnsName", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string DomainDnsName
		{
			get
			{
				return this._DomainDnsName;
			}
			set
			{
				if ((this._DomainDnsName != value))
				{
					this.OnDomainDnsNameChanging(value);
					this.SendPropertyChanging();
					this._DomainDnsName = value;
					this.SendPropertyChanged("DomainDnsName");
					this.OnDomainDnsNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JumpServer1", DbType="NVarChar(256)")]
		public string JumpServer1
		{
			get
			{
				return this._JumpServer1;
			}
			set
			{
				if ((this._JumpServer1 != value))
				{
					this.OnJumpServer1Changing(value);
					this.SendPropertyChanging();
					this._JumpServer1 = value;
					this.SendPropertyChanged("JumpServer1");
					this.OnJumpServer1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JumpServer2", DbType="NVarChar(256)")]
		public string JumpServer2
		{
			get
			{
				return this._JumpServer2;
			}
			set
			{
				if ((this._JumpServer2 != value))
				{
					this.OnJumpServer2Changing(value);
					this.SendPropertyChanging();
					this._JumpServer2 = value;
					this.SendPropertyChanged("JumpServer2");
					this.OnJumpServer2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JumpServer3", DbType="NVarChar(256)")]
		public string JumpServer3
		{
			get
			{
				return this._JumpServer3;
			}
			set
			{
				if ((this._JumpServer3 != value))
				{
					this.OnJumpServer3Changing(value);
					this.SendPropertyChanging();
					this._JumpServer3 = value;
					this.SendPropertyChanged("JumpServer3");
					this.OnJumpServer3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JumpServer4", DbType="NVarChar(256)")]
		public string JumpServer4
		{
			get
			{
				return this._JumpServer4;
			}
			set
			{
				if ((this._JumpServer4 != value))
				{
					this.OnJumpServer4Changing(value);
					this.SendPropertyChanging();
					this._JumpServer4 = value;
					this.SendPropertyChanged("JumpServer4");
					this.OnJumpServer4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Notes", DbType="NVarChar(1024)")]
		public string Notes
		{
			get
			{
				return this._Notes;
			}
			set
			{
				if ((this._Notes != value))
				{
					this.OnNotesChanging(value);
					this.SendPropertyChanging();
					this._Notes = value;
					this.SendPropertyChanged("Notes");
					this.OnNotesChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ManagedEntityType")]
	public partial class ManagedEntityType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ManagedEntityTypeRowId;
		
		private string _ManagedEntityTypeSystemName;
		
		private string _Description;
		
		private System.Nullable<int> _ManagedEntityTypeSQLId;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnManagedEntityTypeRowIdChanging(int value);
    partial void OnManagedEntityTypeRowIdChanged();
    partial void OnManagedEntityTypeSystemNameChanging(string value);
    partial void OnManagedEntityTypeSystemNameChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnManagedEntityTypeSQLIdChanging(System.Nullable<int> value);
    partial void OnManagedEntityTypeSQLIdChanged();
    #endregion
		
		public ManagedEntityType()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManagedEntityTypeRowId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ManagedEntityTypeRowId
		{
			get
			{
				return this._ManagedEntityTypeRowId;
			}
			set
			{
				if ((this._ManagedEntityTypeRowId != value))
				{
					this.OnManagedEntityTypeRowIdChanging(value);
					this.SendPropertyChanging();
					this._ManagedEntityTypeRowId = value;
					this.SendPropertyChanged("ManagedEntityTypeRowId");
					this.OnManagedEntityTypeRowIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManagedEntityTypeSystemName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string ManagedEntityTypeSystemName
		{
			get
			{
				return this._ManagedEntityTypeSystemName;
			}
			set
			{
				if ((this._ManagedEntityTypeSystemName != value))
				{
					this.OnManagedEntityTypeSystemNameChanging(value);
					this.SendPropertyChanging();
					this._ManagedEntityTypeSystemName = value;
					this.SendPropertyChanged("ManagedEntityTypeSystemName");
					this.OnManagedEntityTypeSystemNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(255)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManagedEntityTypeSQLId", DbType="Int")]
		public System.Nullable<int> ManagedEntityTypeSQLId
		{
			get
			{
				return this._ManagedEntityTypeSQLId;
			}
			set
			{
				if ((this._ManagedEntityTypeSQLId != value))
				{
					this.OnManagedEntityTypeSQLIdChanging(value);
					this.SendPropertyChanging();
					this._ManagedEntityTypeSQLId = value;
					this.SendPropertyChanged("ManagedEntityTypeSQLId");
					this.OnManagedEntityTypeSQLIdChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ManagedEntityTypeDBS")]
	public partial class ManagedEntityTypeDBS
	{
		
		private int _ManagedEntityTypeRowId;
		
		private System.Guid _ManagedEntityTypeGuid;
		
		private int _ManagementPackRowId;
		
		private string _ManagedEntityTypeSystemName;
		
		private string _ManagedEntityTypeDefaultName;
		
		private string _ManagedEntityTypeDefaultDescription;
		
		public ManagedEntityTypeDBS()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManagedEntityTypeRowId", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int ManagedEntityTypeRowId
		{
			get
			{
				return this._ManagedEntityTypeRowId;
			}
			set
			{
				if ((this._ManagedEntityTypeRowId != value))
				{
					this._ManagedEntityTypeRowId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManagedEntityTypeGuid", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ManagedEntityTypeGuid
		{
			get
			{
				return this._ManagedEntityTypeGuid;
			}
			set
			{
				if ((this._ManagedEntityTypeGuid != value))
				{
					this._ManagedEntityTypeGuid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManagementPackRowId", DbType="Int NOT NULL")]
		public int ManagementPackRowId
		{
			get
			{
				return this._ManagementPackRowId;
			}
			set
			{
				if ((this._ManagementPackRowId != value))
				{
					this._ManagementPackRowId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManagedEntityTypeSystemName", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string ManagedEntityTypeSystemName
		{
			get
			{
				return this._ManagedEntityTypeSystemName;
			}
			set
			{
				if ((this._ManagedEntityTypeSystemName != value))
				{
					this._ManagedEntityTypeSystemName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManagedEntityTypeDefaultName", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string ManagedEntityTypeDefaultName
		{
			get
			{
				return this._ManagedEntityTypeDefaultName;
			}
			set
			{
				if ((this._ManagedEntityTypeDefaultName != value))
				{
					this._ManagedEntityTypeDefaultName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManagedEntityTypeDefaultDescription", DbType="NVarChar(MAX)")]
		public string ManagedEntityTypeDefaultDescription
		{
			get
			{
				return this._ManagedEntityTypeDefaultDescription;
			}
			set
			{
				if ((this._ManagedEntityTypeDefaultDescription != value))
				{
					this._ManagedEntityTypeDefaultDescription = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProductVersion")]
	public partial class ProductVersion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _productversion1;
		
		private string _sqlversion;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onproductversion1Changing(string value);
    partial void Onproductversion1Changed();
    partial void OnsqlversionChanging(string value);
    partial void OnsqlversionChanged();
    #endregion
		
		public ProductVersion()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="productversion", Storage="_productversion1", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string productversion1
		{
			get
			{
				return this._productversion1;
			}
			set
			{
				if ((this._productversion1 != value))
				{
					this.Onproductversion1Changing(value);
					this.SendPropertyChanging();
					this._productversion1 = value;
					this.SendPropertyChanged("productversion1");
					this.Onproductversion1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sqlversion", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string sqlversion
		{
			get
			{
				return this._sqlversion;
			}
			set
			{
				if ((this._sqlversion != value))
				{
					this.OnsqlversionChanging(value);
					this.SendPropertyChanging();
					this._sqlversion = value;
					this.SendPropertyChanged("sqlversion");
					this.OnsqlversionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SQLComputer")]
	public partial class SQLComputer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private long _ManagedEntityRowId;
		
		private string _DisplayName;
		
		private string _DNSName;
		
		private string _DomainDnsName;
		
		private string _IPAddress;
		
		private System.Nullable<int> _LogicalProcessors;
		
		private string _NetbiosComputerName;
		
		private string _NetworkName;
		
		private string _OrganizationalUnit;
		
		private System.Nullable<int> _PhysicalProcessors;
		
		private string _PrincipalName;
		
		private string _SQLCustomer;
		
		private string _SQLMandant;
		
		private string _SQLMonitoringType;
		
		private string _Virtual_Server_Type;
		
		private string _VirtualMachineName;
		
		private System.Nullable<System.DateTime> _Modified;
		
		private System.DateTime _Insterted;
		
		private System.Nullable<System.DateTime> _UpDateDate;
		
		private bool _IsSCOM;
		
		private System.Nullable<System.DateTime> _NotFoundSince;
		
		private System.Nullable<int> _NotFoundSinceDays;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnManagedEntityRowIdChanging(long value);
    partial void OnManagedEntityRowIdChanged();
    partial void OnDisplayNameChanging(string value);
    partial void OnDisplayNameChanged();
    partial void OnDNSNameChanging(string value);
    partial void OnDNSNameChanged();
    partial void OnDomainDnsNameChanging(string value);
    partial void OnDomainDnsNameChanged();
    partial void OnIPAddressChanging(string value);
    partial void OnIPAddressChanged();
    partial void OnLogicalProcessorsChanging(System.Nullable<int> value);
    partial void OnLogicalProcessorsChanged();
    partial void OnNetbiosComputerNameChanging(string value);
    partial void OnNetbiosComputerNameChanged();
    partial void OnNetworkNameChanging(string value);
    partial void OnNetworkNameChanged();
    partial void OnOrganizationalUnitChanging(string value);
    partial void OnOrganizationalUnitChanged();
    partial void OnPhysicalProcessorsChanging(System.Nullable<int> value);
    partial void OnPhysicalProcessorsChanged();
    partial void OnPrincipalNameChanging(string value);
    partial void OnPrincipalNameChanged();
    partial void OnSQLCustomerChanging(string value);
    partial void OnSQLCustomerChanged();
    partial void OnSQLMandantChanging(string value);
    partial void OnSQLMandantChanged();
    partial void OnSQLMonitoringTypeChanging(string value);
    partial void OnSQLMonitoringTypeChanged();
    partial void OnVirtual_Server_TypeChanging(string value);
    partial void OnVirtual_Server_TypeChanged();
    partial void OnVirtualMachineNameChanging(string value);
    partial void OnVirtualMachineNameChanged();
    partial void OnModifiedChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedChanged();
    partial void OnInstertedChanging(System.DateTime value);
    partial void OnInstertedChanged();
    partial void OnUpDateDateChanging(System.Nullable<System.DateTime> value);
    partial void OnUpDateDateChanged();
    partial void OnIsSCOMChanging(bool value);
    partial void OnIsSCOMChanged();
    partial void OnNotFoundSinceChanging(System.Nullable<System.DateTime> value);
    partial void OnNotFoundSinceChanged();
    partial void OnNotFoundSinceDaysChanging(System.Nullable<int> value);
    partial void OnNotFoundSinceDaysChanged();
    #endregion
		
		public SQLComputer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="BigInt NOT NULL IDENTITY", IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManagedEntityRowId", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long ManagedEntityRowId
		{
			get
			{
				return this._ManagedEntityRowId;
			}
			set
			{
				if ((this._ManagedEntityRowId != value))
				{
					this.OnManagedEntityRowIdChanging(value);
					this.SendPropertyChanging();
					this._ManagedEntityRowId = value;
					this.SendPropertyChanged("ManagedEntityRowId");
					this.OnManagedEntityRowIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayName", DbType="NVarChar(256)")]
		public string DisplayName
		{
			get
			{
				return this._DisplayName;
			}
			set
			{
				if ((this._DisplayName != value))
				{
					this.OnDisplayNameChanging(value);
					this.SendPropertyChanging();
					this._DisplayName = value;
					this.SendPropertyChanged("DisplayName");
					this.OnDisplayNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DNSName", DbType="NVarChar(256)")]
		public string DNSName
		{
			get
			{
				return this._DNSName;
			}
			set
			{
				if ((this._DNSName != value))
				{
					this.OnDNSNameChanging(value);
					this.SendPropertyChanging();
					this._DNSName = value;
					this.SendPropertyChanged("DNSName");
					this.OnDNSNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DomainDnsName", DbType="NVarChar(256)")]
		public string DomainDnsName
		{
			get
			{
				return this._DomainDnsName;
			}
			set
			{
				if ((this._DomainDnsName != value))
				{
					this.OnDomainDnsNameChanging(value);
					this.SendPropertyChanging();
					this._DomainDnsName = value;
					this.SendPropertyChanged("DomainDnsName");
					this.OnDomainDnsNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IPAddress", DbType="NVarChar(256)")]
		public string IPAddress
		{
			get
			{
				return this._IPAddress;
			}
			set
			{
				if ((this._IPAddress != value))
				{
					this.OnIPAddressChanging(value);
					this.SendPropertyChanging();
					this._IPAddress = value;
					this.SendPropertyChanged("IPAddress");
					this.OnIPAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogicalProcessors", DbType="Int")]
		public System.Nullable<int> LogicalProcessors
		{
			get
			{
				return this._LogicalProcessors;
			}
			set
			{
				if ((this._LogicalProcessors != value))
				{
					this.OnLogicalProcessorsChanging(value);
					this.SendPropertyChanging();
					this._LogicalProcessors = value;
					this.SendPropertyChanged("LogicalProcessors");
					this.OnLogicalProcessorsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NetbiosComputerName", DbType="NVarChar(256)")]
		public string NetbiosComputerName
		{
			get
			{
				return this._NetbiosComputerName;
			}
			set
			{
				if ((this._NetbiosComputerName != value))
				{
					this.OnNetbiosComputerNameChanging(value);
					this.SendPropertyChanging();
					this._NetbiosComputerName = value;
					this.SendPropertyChanged("NetbiosComputerName");
					this.OnNetbiosComputerNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NetworkName", DbType="NVarChar(256)")]
		public string NetworkName
		{
			get
			{
				return this._NetworkName;
			}
			set
			{
				if ((this._NetworkName != value))
				{
					this.OnNetworkNameChanging(value);
					this.SendPropertyChanging();
					this._NetworkName = value;
					this.SendPropertyChanged("NetworkName");
					this.OnNetworkNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrganizationalUnit", DbType="NVarChar(256)")]
		public string OrganizationalUnit
		{
			get
			{
				return this._OrganizationalUnit;
			}
			set
			{
				if ((this._OrganizationalUnit != value))
				{
					this.OnOrganizationalUnitChanging(value);
					this.SendPropertyChanging();
					this._OrganizationalUnit = value;
					this.SendPropertyChanged("OrganizationalUnit");
					this.OnOrganizationalUnitChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhysicalProcessors", DbType="Int")]
		public System.Nullable<int> PhysicalProcessors
		{
			get
			{
				return this._PhysicalProcessors;
			}
			set
			{
				if ((this._PhysicalProcessors != value))
				{
					this.OnPhysicalProcessorsChanging(value);
					this.SendPropertyChanging();
					this._PhysicalProcessors = value;
					this.SendPropertyChanged("PhysicalProcessors");
					this.OnPhysicalProcessorsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrincipalName", DbType="NVarChar(256)")]
		public string PrincipalName
		{
			get
			{
				return this._PrincipalName;
			}
			set
			{
				if ((this._PrincipalName != value))
				{
					this.OnPrincipalNameChanging(value);
					this.SendPropertyChanging();
					this._PrincipalName = value;
					this.SendPropertyChanged("PrincipalName");
					this.OnPrincipalNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SQLCustomer", AutoSync=AutoSync.Always, DbType="VarChar(250)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string SQLCustomer
		{
			get
			{
				return this._SQLCustomer;
			}
			set
			{
				if ((this._SQLCustomer != value))
				{
					this.OnSQLCustomerChanging(value);
					this.SendPropertyChanging();
					this._SQLCustomer = value;
					this.SendPropertyChanged("SQLCustomer");
					this.OnSQLCustomerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SQLMandant", DbType="NVarChar(256)")]
		public string SQLMandant
		{
			get
			{
				return this._SQLMandant;
			}
			set
			{
				if ((this._SQLMandant != value))
				{
					this.OnSQLMandantChanging(value);
					this.SendPropertyChanging();
					this._SQLMandant = value;
					this.SendPropertyChanged("SQLMandant");
					this.OnSQLMandantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SQLMonitoringType", DbType="NVarChar(256)")]
		public string SQLMonitoringType
		{
			get
			{
				return this._SQLMonitoringType;
			}
			set
			{
				if ((this._SQLMonitoringType != value))
				{
					this.OnSQLMonitoringTypeChanging(value);
					this.SendPropertyChanging();
					this._SQLMonitoringType = value;
					this.SendPropertyChanged("SQLMonitoringType");
					this.OnSQLMonitoringTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Virtual_Server_Type", DbType="NVarChar(256)")]
		public string Virtual_Server_Type
		{
			get
			{
				return this._Virtual_Server_Type;
			}
			set
			{
				if ((this._Virtual_Server_Type != value))
				{
					this.OnVirtual_Server_TypeChanging(value);
					this.SendPropertyChanging();
					this._Virtual_Server_Type = value;
					this.SendPropertyChanged("Virtual_Server_Type");
					this.OnVirtual_Server_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VirtualMachineName", DbType="NVarChar(256)")]
		public string VirtualMachineName
		{
			get
			{
				return this._VirtualMachineName;
			}
			set
			{
				if ((this._VirtualMachineName != value))
				{
					this.OnVirtualMachineNameChanging(value);
					this.SendPropertyChanging();
					this._VirtualMachineName = value;
					this.SendPropertyChanged("VirtualMachineName");
					this.OnVirtualMachineNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modified", DbType="Date")]
		public System.Nullable<System.DateTime> Modified
		{
			get
			{
				return this._Modified;
			}
			set
			{
				if ((this._Modified != value))
				{
					this.OnModifiedChanging(value);
					this.SendPropertyChanging();
					this._Modified = value;
					this.SendPropertyChanged("Modified");
					this.OnModifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Insterted", DbType="Date NOT NULL")]
		public System.DateTime Insterted
		{
			get
			{
				return this._Insterted;
			}
			set
			{
				if ((this._Insterted != value))
				{
					this.OnInstertedChanging(value);
					this.SendPropertyChanging();
					this._Insterted = value;
					this.SendPropertyChanged("Insterted");
					this.OnInstertedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UpDateDate", DbType="Date")]
		public System.Nullable<System.DateTime> UpDateDate
		{
			get
			{
				return this._UpDateDate;
			}
			set
			{
				if ((this._UpDateDate != value))
				{
					this.OnUpDateDateChanging(value);
					this.SendPropertyChanging();
					this._UpDateDate = value;
					this.SendPropertyChanged("UpDateDate");
					this.OnUpDateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSCOM", DbType="Bit NOT NULL")]
		public bool IsSCOM
		{
			get
			{
				return this._IsSCOM;
			}
			set
			{
				if ((this._IsSCOM != value))
				{
					this.OnIsSCOMChanging(value);
					this.SendPropertyChanging();
					this._IsSCOM = value;
					this.SendPropertyChanged("IsSCOM");
					this.OnIsSCOMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotFoundSince", DbType="Date")]
		public System.Nullable<System.DateTime> NotFoundSince
		{
			get
			{
				return this._NotFoundSince;
			}
			set
			{
				if ((this._NotFoundSince != value))
				{
					this.OnNotFoundSinceChanging(value);
					this.SendPropertyChanging();
					this._NotFoundSince = value;
					this.SendPropertyChanged("NotFoundSince");
					this.OnNotFoundSinceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotFoundSinceDays", AutoSync=AutoSync.Always, DbType="Int", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> NotFoundSinceDays
		{
			get
			{
				return this._NotFoundSinceDays;
			}
			set
			{
				if ((this._NotFoundSinceDays != value))
				{
					this.OnNotFoundSinceDaysChanging(value);
					this.SendPropertyChanging();
					this._NotFoundSinceDays = value;
					this.SendPropertyChanged("NotFoundSinceDays");
					this.OnNotFoundSinceDaysChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SQLDatabases")]
	public partial class SQLDatabases : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private System.Nullable<long> _ManagedEntityRowId;
		
		private System.Nullable<long> _TopLevelHostManagedEntityRowId;
		
		private string _Collation;
		
		private string _DatabaseAutogrow;
		
		private string _DatabaseName;
		
		private string _LogAutogrow;
		
		private string _Owner;
		
		private string _RecoveryModel;
		
		private string _Updateability;
		
		private string _UserAccess;
		
		private System.Nullable<System.DateTime> _NotFoundSince;
		
		private System.Nullable<int> _NotFoundSinceDays;
		
		private System.Nullable<System.DateTime> _Modified;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnManagedEntityRowIdChanging(System.Nullable<long> value);
    partial void OnManagedEntityRowIdChanged();
    partial void OnTopLevelHostManagedEntityRowIdChanging(System.Nullable<long> value);
    partial void OnTopLevelHostManagedEntityRowIdChanged();
    partial void OnCollationChanging(string value);
    partial void OnCollationChanged();
    partial void OnDatabaseAutogrowChanging(string value);
    partial void OnDatabaseAutogrowChanged();
    partial void OnDatabaseNameChanging(string value);
    partial void OnDatabaseNameChanged();
    partial void OnLogAutogrowChanging(string value);
    partial void OnLogAutogrowChanged();
    partial void OnOwnerChanging(string value);
    partial void OnOwnerChanged();
    partial void OnRecoveryModelChanging(string value);
    partial void OnRecoveryModelChanged();
    partial void OnUpdateabilityChanging(string value);
    partial void OnUpdateabilityChanged();
    partial void OnUserAccessChanging(string value);
    partial void OnUserAccessChanged();
    partial void OnNotFoundSinceChanging(System.Nullable<System.DateTime> value);
    partial void OnNotFoundSinceChanged();
    partial void OnNotFoundSinceDaysChanging(System.Nullable<int> value);
    partial void OnNotFoundSinceDaysChanged();
    partial void OnModifiedChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedChanged();
    #endregion
		
		public SQLDatabases()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManagedEntityRowId", DbType="BigInt")]
		public System.Nullable<long> ManagedEntityRowId
		{
			get
			{
				return this._ManagedEntityRowId;
			}
			set
			{
				if ((this._ManagedEntityRowId != value))
				{
					this.OnManagedEntityRowIdChanging(value);
					this.SendPropertyChanging();
					this._ManagedEntityRowId = value;
					this.SendPropertyChanged("ManagedEntityRowId");
					this.OnManagedEntityRowIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TopLevelHostManagedEntityRowId", DbType="BigInt")]
		public System.Nullable<long> TopLevelHostManagedEntityRowId
		{
			get
			{
				return this._TopLevelHostManagedEntityRowId;
			}
			set
			{
				if ((this._TopLevelHostManagedEntityRowId != value))
				{
					this.OnTopLevelHostManagedEntityRowIdChanging(value);
					this.SendPropertyChanging();
					this._TopLevelHostManagedEntityRowId = value;
					this.SendPropertyChanged("TopLevelHostManagedEntityRowId");
					this.OnTopLevelHostManagedEntityRowIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Collation", DbType="NVarChar(255)")]
		public string Collation
		{
			get
			{
				return this._Collation;
			}
			set
			{
				if ((this._Collation != value))
				{
					this.OnCollationChanging(value);
					this.SendPropertyChanging();
					this._Collation = value;
					this.SendPropertyChanged("Collation");
					this.OnCollationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatabaseAutogrow", DbType="NVarChar(255)")]
		public string DatabaseAutogrow
		{
			get
			{
				return this._DatabaseAutogrow;
			}
			set
			{
				if ((this._DatabaseAutogrow != value))
				{
					this.OnDatabaseAutogrowChanging(value);
					this.SendPropertyChanging();
					this._DatabaseAutogrow = value;
					this.SendPropertyChanged("DatabaseAutogrow");
					this.OnDatabaseAutogrowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatabaseName", DbType="NVarChar(255)")]
		public string DatabaseName
		{
			get
			{
				return this._DatabaseName;
			}
			set
			{
				if ((this._DatabaseName != value))
				{
					this.OnDatabaseNameChanging(value);
					this.SendPropertyChanging();
					this._DatabaseName = value;
					this.SendPropertyChanged("DatabaseName");
					this.OnDatabaseNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogAutogrow", DbType="NVarChar(255)")]
		public string LogAutogrow
		{
			get
			{
				return this._LogAutogrow;
			}
			set
			{
				if ((this._LogAutogrow != value))
				{
					this.OnLogAutogrowChanging(value);
					this.SendPropertyChanging();
					this._LogAutogrow = value;
					this.SendPropertyChanged("LogAutogrow");
					this.OnLogAutogrowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Owner", DbType="NVarChar(255)")]
		public string Owner
		{
			get
			{
				return this._Owner;
			}
			set
			{
				if ((this._Owner != value))
				{
					this.OnOwnerChanging(value);
					this.SendPropertyChanging();
					this._Owner = value;
					this.SendPropertyChanged("Owner");
					this.OnOwnerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecoveryModel", DbType="NVarChar(255)")]
		public string RecoveryModel
		{
			get
			{
				return this._RecoveryModel;
			}
			set
			{
				if ((this._RecoveryModel != value))
				{
					this.OnRecoveryModelChanging(value);
					this.SendPropertyChanging();
					this._RecoveryModel = value;
					this.SendPropertyChanged("RecoveryModel");
					this.OnRecoveryModelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Updateability", DbType="NVarChar(255)")]
		public string Updateability
		{
			get
			{
				return this._Updateability;
			}
			set
			{
				if ((this._Updateability != value))
				{
					this.OnUpdateabilityChanging(value);
					this.SendPropertyChanging();
					this._Updateability = value;
					this.SendPropertyChanged("Updateability");
					this.OnUpdateabilityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserAccess", DbType="NVarChar(255)")]
		public string UserAccess
		{
			get
			{
				return this._UserAccess;
			}
			set
			{
				if ((this._UserAccess != value))
				{
					this.OnUserAccessChanging(value);
					this.SendPropertyChanging();
					this._UserAccess = value;
					this.SendPropertyChanged("UserAccess");
					this.OnUserAccessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotFoundSince", DbType="Date")]
		public System.Nullable<System.DateTime> NotFoundSince
		{
			get
			{
				return this._NotFoundSince;
			}
			set
			{
				if ((this._NotFoundSince != value))
				{
					this.OnNotFoundSinceChanging(value);
					this.SendPropertyChanging();
					this._NotFoundSince = value;
					this.SendPropertyChanged("NotFoundSince");
					this.OnNotFoundSinceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotFoundSinceDays", AutoSync=AutoSync.Always, DbType="Int", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> NotFoundSinceDays
		{
			get
			{
				return this._NotFoundSinceDays;
			}
			set
			{
				if ((this._NotFoundSinceDays != value))
				{
					this.OnNotFoundSinceDaysChanging(value);
					this.SendPropertyChanging();
					this._NotFoundSinceDays = value;
					this.SendPropertyChanged("NotFoundSinceDays");
					this.OnNotFoundSinceDaysChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modified", DbType="Date")]
		public System.Nullable<System.DateTime> Modified
		{
			get
			{
				return this._Modified;
			}
			set
			{
				if ((this._Modified != value))
				{
					this.OnModifiedChanging(value);
					this.SendPropertyChanging();
					this._Modified = value;
					this.SendPropertyChanged("Modified");
					this.OnModifiedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SQLInstallType")]
	public partial class SQLInstallType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _Type;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    #endregion
		
		public SQLInstallType()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="NVarChar(50)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SQLServer")]
	public partial class SQLServer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private long _ManagedEntityRowId;
		
		private System.Nullable<long> _TopLevelHostManagedEntityRowId;
		
		private string _SQLMandantName;
		
		private string _Path;
		
		private string _Account;
		
		private string _AgentClusterName;
		
		private string _AgentName;
		
		private string _AuditLevel;
		
		private string _AuthenticationMode;
		
		private string _Cluster;
		
		private string _ConnectionString;
		
		private string _DisplayName;
		
		private string _Domain;
		
		private string _Edition;
		
		private string _EnableErrorReporting;
		
		private string _ErrorLogLocation;
		
		private string _FullName;
		
		private string _FullTextSearchServiceClusterName;
		
		private string _FullTextSearchServiceName;
		
		private string _InstallPath;
		
		private string _InstanceID;
		
		private string _InstanceName;
		
		private string _Language;
		
		private string _MasterDatabaseLocation;
		
		private string _MasterDatabaseLogLocation;
		
		private string _PrincipalName;
		
		private string _ReplicationDistributionDatabase;
		
		private string _ReplicationWorkingDirectory;
		
		private string _ServiceClusterName;
		
		private string _ServiceName;
		
		private string _ServicePackVersion;
		
		private string _TcpPort;
		
		private string _ToolsPath;
		
		private string _Type;
		
		private string _Version;
		
		private string _VersionNr;
		
		private System.Nullable<System.DateTime> _Modified;
		
		private System.DateTime _Insterted;
		
		private bool _IsSCOM;
		
		private System.Nullable<System.DateTime> _NotFoundSince;
		
		private System.Nullable<int> _NotFoundSinceDay;
		
    #region Definitionen der Erweiterungsmethoden
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnManagedEntityRowIdChanging(long value);
    partial void OnManagedEntityRowIdChanged();
    partial void OnTopLevelHostManagedEntityRowIdChanging(System.Nullable<long> value);
    partial void OnTopLevelHostManagedEntityRowIdChanged();
    partial void OnSQLMandantNameChanging(string value);
    partial void OnSQLMandantNameChanged();
    partial void OnPathChanging(string value);
    partial void OnPathChanged();
    partial void OnAccountChanging(string value);
    partial void OnAccountChanged();
    partial void OnAgentClusterNameChanging(string value);
    partial void OnAgentClusterNameChanged();
    partial void OnAgentNameChanging(string value);
    partial void OnAgentNameChanged();
    partial void OnAuditLevelChanging(string value);
    partial void OnAuditLevelChanged();
    partial void OnAuthenticationModeChanging(string value);
    partial void OnAuthenticationModeChanged();
    partial void OnClusterChanging(string value);
    partial void OnClusterChanged();
    partial void OnConnectionStringChanging(string value);
    partial void OnConnectionStringChanged();
    partial void OnDisplayNameChanging(string value);
    partial void OnDisplayNameChanged();
    partial void OnDomainChanging(string value);
    partial void OnDomainChanged();
    partial void OnEditionChanging(string value);
    partial void OnEditionChanged();
    partial void OnEnableErrorReportingChanging(string value);
    partial void OnEnableErrorReportingChanged();
    partial void OnErrorLogLocationChanging(string value);
    partial void OnErrorLogLocationChanged();
    partial void OnFullNameChanging(string value);
    partial void OnFullNameChanged();
    partial void OnFullTextSearchServiceClusterNameChanging(string value);
    partial void OnFullTextSearchServiceClusterNameChanged();
    partial void OnFullTextSearchServiceNameChanging(string value);
    partial void OnFullTextSearchServiceNameChanged();
    partial void OnInstallPathChanging(string value);
    partial void OnInstallPathChanged();
    partial void OnInstanceIDChanging(string value);
    partial void OnInstanceIDChanged();
    partial void OnInstanceNameChanging(string value);
    partial void OnInstanceNameChanged();
    partial void OnLanguageChanging(string value);
    partial void OnLanguageChanged();
    partial void OnMasterDatabaseLocationChanging(string value);
    partial void OnMasterDatabaseLocationChanged();
    partial void OnMasterDatabaseLogLocationChanging(string value);
    partial void OnMasterDatabaseLogLocationChanged();
    partial void OnPrincipalNameChanging(string value);
    partial void OnPrincipalNameChanged();
    partial void OnReplicationDistributionDatabaseChanging(string value);
    partial void OnReplicationDistributionDatabaseChanged();
    partial void OnReplicationWorkingDirectoryChanging(string value);
    partial void OnReplicationWorkingDirectoryChanged();
    partial void OnServiceClusterNameChanging(string value);
    partial void OnServiceClusterNameChanged();
    partial void OnServiceNameChanging(string value);
    partial void OnServiceNameChanged();
    partial void OnServicePackVersionChanging(string value);
    partial void OnServicePackVersionChanged();
    partial void OnTcpPortChanging(string value);
    partial void OnTcpPortChanged();
    partial void OnToolsPathChanging(string value);
    partial void OnToolsPathChanged();
    partial void OnTypeChanging(string value);
    partial void OnTypeChanged();
    partial void OnVersionChanging(string value);
    partial void OnVersionChanged();
    partial void OnVersionNrChanging(string value);
    partial void OnVersionNrChanged();
    partial void OnModifiedChanging(System.Nullable<System.DateTime> value);
    partial void OnModifiedChanged();
    partial void OnInstertedChanging(System.DateTime value);
    partial void OnInstertedChanged();
    partial void OnIsSCOMChanging(bool value);
    partial void OnIsSCOMChanged();
    partial void OnNotFoundSinceChanging(System.Nullable<System.DateTime> value);
    partial void OnNotFoundSinceChanged();
    partial void OnNotFoundSinceDayChanging(System.Nullable<int> value);
    partial void OnNotFoundSinceDayChanged();
    #endregion
		
		public SQLServer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.Always, DbType="BigInt NOT NULL IDENTITY", IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManagedEntityRowId", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long ManagedEntityRowId
		{
			get
			{
				return this._ManagedEntityRowId;
			}
			set
			{
				if ((this._ManagedEntityRowId != value))
				{
					this.OnManagedEntityRowIdChanging(value);
					this.SendPropertyChanging();
					this._ManagedEntityRowId = value;
					this.SendPropertyChanged("ManagedEntityRowId");
					this.OnManagedEntityRowIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TopLevelHostManagedEntityRowId", DbType="BigInt")]
		public System.Nullable<long> TopLevelHostManagedEntityRowId
		{
			get
			{
				return this._TopLevelHostManagedEntityRowId;
			}
			set
			{
				if ((this._TopLevelHostManagedEntityRowId != value))
				{
					this.OnTopLevelHostManagedEntityRowIdChanging(value);
					this.SendPropertyChanging();
					this._TopLevelHostManagedEntityRowId = value;
					this.SendPropertyChanged("TopLevelHostManagedEntityRowId");
					this.OnTopLevelHostManagedEntityRowIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SQLMandantName", AutoSync=AutoSync.Always, DbType="VarChar(250)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string SQLMandantName
		{
			get
			{
				return this._SQLMandantName;
			}
			set
			{
				if ((this._SQLMandantName != value))
				{
					this.OnSQLMandantNameChanging(value);
					this.SendPropertyChanging();
					this._SQLMandantName = value;
					this.SendPropertyChanged("SQLMandantName");
					this.OnSQLMandantNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Path", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string Path
		{
			get
			{
				return this._Path;
			}
			set
			{
				if ((this._Path != value))
				{
					this.OnPathChanging(value);
					this.SendPropertyChanging();
					this._Path = value;
					this.SendPropertyChanged("Path");
					this.OnPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Account", DbType="NVarChar(256)")]
		public string Account
		{
			get
			{
				return this._Account;
			}
			set
			{
				if ((this._Account != value))
				{
					this.OnAccountChanging(value);
					this.SendPropertyChanging();
					this._Account = value;
					this.SendPropertyChanged("Account");
					this.OnAccountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgentClusterName", DbType="NVarChar(256)")]
		public string AgentClusterName
		{
			get
			{
				return this._AgentClusterName;
			}
			set
			{
				if ((this._AgentClusterName != value))
				{
					this.OnAgentClusterNameChanging(value);
					this.SendPropertyChanging();
					this._AgentClusterName = value;
					this.SendPropertyChanged("AgentClusterName");
					this.OnAgentClusterNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AgentName", DbType="NVarChar(256)")]
		public string AgentName
		{
			get
			{
				return this._AgentName;
			}
			set
			{
				if ((this._AgentName != value))
				{
					this.OnAgentNameChanging(value);
					this.SendPropertyChanging();
					this._AgentName = value;
					this.SendPropertyChanged("AgentName");
					this.OnAgentNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuditLevel", DbType="NVarChar(256)")]
		public string AuditLevel
		{
			get
			{
				return this._AuditLevel;
			}
			set
			{
				if ((this._AuditLevel != value))
				{
					this.OnAuditLevelChanging(value);
					this.SendPropertyChanging();
					this._AuditLevel = value;
					this.SendPropertyChanged("AuditLevel");
					this.OnAuditLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AuthenticationMode", DbType="NVarChar(256)")]
		public string AuthenticationMode
		{
			get
			{
				return this._AuthenticationMode;
			}
			set
			{
				if ((this._AuthenticationMode != value))
				{
					this.OnAuthenticationModeChanging(value);
					this.SendPropertyChanging();
					this._AuthenticationMode = value;
					this.SendPropertyChanged("AuthenticationMode");
					this.OnAuthenticationModeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cluster", DbType="NVarChar(256)")]
		public string Cluster
		{
			get
			{
				return this._Cluster;
			}
			set
			{
				if ((this._Cluster != value))
				{
					this.OnClusterChanging(value);
					this.SendPropertyChanging();
					this._Cluster = value;
					this.SendPropertyChanged("Cluster");
					this.OnClusterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConnectionString", DbType="NVarChar(256)")]
		public string ConnectionString
		{
			get
			{
				return this._ConnectionString;
			}
			set
			{
				if ((this._ConnectionString != value))
				{
					this.OnConnectionStringChanging(value);
					this.SendPropertyChanging();
					this._ConnectionString = value;
					this.SendPropertyChanged("ConnectionString");
					this.OnConnectionStringChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayName", DbType="NVarChar(256)")]
		public string DisplayName
		{
			get
			{
				return this._DisplayName;
			}
			set
			{
				if ((this._DisplayName != value))
				{
					this.OnDisplayNameChanging(value);
					this.SendPropertyChanging();
					this._DisplayName = value;
					this.SendPropertyChanged("DisplayName");
					this.OnDisplayNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Domain", DbType="NVarChar(256)")]
		public string Domain
		{
			get
			{
				return this._Domain;
			}
			set
			{
				if ((this._Domain != value))
				{
					this.OnDomainChanging(value);
					this.SendPropertyChanging();
					this._Domain = value;
					this.SendPropertyChanged("Domain");
					this.OnDomainChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Edition", DbType="NVarChar(256)")]
		public string Edition
		{
			get
			{
				return this._Edition;
			}
			set
			{
				if ((this._Edition != value))
				{
					this.OnEditionChanging(value);
					this.SendPropertyChanging();
					this._Edition = value;
					this.SendPropertyChanged("Edition");
					this.OnEditionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EnableErrorReporting", DbType="NVarChar(256)")]
		public string EnableErrorReporting
		{
			get
			{
				return this._EnableErrorReporting;
			}
			set
			{
				if ((this._EnableErrorReporting != value))
				{
					this.OnEnableErrorReportingChanging(value);
					this.SendPropertyChanging();
					this._EnableErrorReporting = value;
					this.SendPropertyChanged("EnableErrorReporting");
					this.OnEnableErrorReportingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorLogLocation", DbType="NVarChar(256)")]
		public string ErrorLogLocation
		{
			get
			{
				return this._ErrorLogLocation;
			}
			set
			{
				if ((this._ErrorLogLocation != value))
				{
					this.OnErrorLogLocationChanging(value);
					this.SendPropertyChanging();
					this._ErrorLogLocation = value;
					this.SendPropertyChanged("ErrorLogLocation");
					this.OnErrorLogLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(256)")]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this.OnFullNameChanging(value);
					this.SendPropertyChanging();
					this._FullName = value;
					this.SendPropertyChanged("FullName");
					this.OnFullNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullTextSearchServiceClusterName", DbType="NVarChar(256)")]
		public string FullTextSearchServiceClusterName
		{
			get
			{
				return this._FullTextSearchServiceClusterName;
			}
			set
			{
				if ((this._FullTextSearchServiceClusterName != value))
				{
					this.OnFullTextSearchServiceClusterNameChanging(value);
					this.SendPropertyChanging();
					this._FullTextSearchServiceClusterName = value;
					this.SendPropertyChanged("FullTextSearchServiceClusterName");
					this.OnFullTextSearchServiceClusterNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullTextSearchServiceName", DbType="NVarChar(256)")]
		public string FullTextSearchServiceName
		{
			get
			{
				return this._FullTextSearchServiceName;
			}
			set
			{
				if ((this._FullTextSearchServiceName != value))
				{
					this.OnFullTextSearchServiceNameChanging(value);
					this.SendPropertyChanging();
					this._FullTextSearchServiceName = value;
					this.SendPropertyChanged("FullTextSearchServiceName");
					this.OnFullTextSearchServiceNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstallPath", DbType="NVarChar(256)")]
		public string InstallPath
		{
			get
			{
				return this._InstallPath;
			}
			set
			{
				if ((this._InstallPath != value))
				{
					this.OnInstallPathChanging(value);
					this.SendPropertyChanging();
					this._InstallPath = value;
					this.SendPropertyChanged("InstallPath");
					this.OnInstallPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstanceID", DbType="NVarChar(256)")]
		public string InstanceID
		{
			get
			{
				return this._InstanceID;
			}
			set
			{
				if ((this._InstanceID != value))
				{
					this.OnInstanceIDChanging(value);
					this.SendPropertyChanging();
					this._InstanceID = value;
					this.SendPropertyChanged("InstanceID");
					this.OnInstanceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstanceName", DbType="NVarChar(256)")]
		public string InstanceName
		{
			get
			{
				return this._InstanceName;
			}
			set
			{
				if ((this._InstanceName != value))
				{
					this.OnInstanceNameChanging(value);
					this.SendPropertyChanging();
					this._InstanceName = value;
					this.SendPropertyChanged("InstanceName");
					this.OnInstanceNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Language", DbType="NVarChar(256)")]
		public string Language
		{
			get
			{
				return this._Language;
			}
			set
			{
				if ((this._Language != value))
				{
					this.OnLanguageChanging(value);
					this.SendPropertyChanging();
					this._Language = value;
					this.SendPropertyChanged("Language");
					this.OnLanguageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MasterDatabaseLocation", DbType="NVarChar(256)")]
		public string MasterDatabaseLocation
		{
			get
			{
				return this._MasterDatabaseLocation;
			}
			set
			{
				if ((this._MasterDatabaseLocation != value))
				{
					this.OnMasterDatabaseLocationChanging(value);
					this.SendPropertyChanging();
					this._MasterDatabaseLocation = value;
					this.SendPropertyChanged("MasterDatabaseLocation");
					this.OnMasterDatabaseLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MasterDatabaseLogLocation", DbType="NVarChar(256)")]
		public string MasterDatabaseLogLocation
		{
			get
			{
				return this._MasterDatabaseLogLocation;
			}
			set
			{
				if ((this._MasterDatabaseLogLocation != value))
				{
					this.OnMasterDatabaseLogLocationChanging(value);
					this.SendPropertyChanging();
					this._MasterDatabaseLogLocation = value;
					this.SendPropertyChanged("MasterDatabaseLogLocation");
					this.OnMasterDatabaseLogLocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrincipalName", DbType="NVarChar(256)")]
		public string PrincipalName
		{
			get
			{
				return this._PrincipalName;
			}
			set
			{
				if ((this._PrincipalName != value))
				{
					this.OnPrincipalNameChanging(value);
					this.SendPropertyChanging();
					this._PrincipalName = value;
					this.SendPropertyChanged("PrincipalName");
					this.OnPrincipalNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReplicationDistributionDatabase", DbType="NVarChar(256)")]
		public string ReplicationDistributionDatabase
		{
			get
			{
				return this._ReplicationDistributionDatabase;
			}
			set
			{
				if ((this._ReplicationDistributionDatabase != value))
				{
					this.OnReplicationDistributionDatabaseChanging(value);
					this.SendPropertyChanging();
					this._ReplicationDistributionDatabase = value;
					this.SendPropertyChanged("ReplicationDistributionDatabase");
					this.OnReplicationDistributionDatabaseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReplicationWorkingDirectory", DbType="NVarChar(256)")]
		public string ReplicationWorkingDirectory
		{
			get
			{
				return this._ReplicationWorkingDirectory;
			}
			set
			{
				if ((this._ReplicationWorkingDirectory != value))
				{
					this.OnReplicationWorkingDirectoryChanging(value);
					this.SendPropertyChanging();
					this._ReplicationWorkingDirectory = value;
					this.SendPropertyChanged("ReplicationWorkingDirectory");
					this.OnReplicationWorkingDirectoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceClusterName", DbType="NVarChar(256)")]
		public string ServiceClusterName
		{
			get
			{
				return this._ServiceClusterName;
			}
			set
			{
				if ((this._ServiceClusterName != value))
				{
					this.OnServiceClusterNameChanging(value);
					this.SendPropertyChanging();
					this._ServiceClusterName = value;
					this.SendPropertyChanged("ServiceClusterName");
					this.OnServiceClusterNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServiceName", DbType="NVarChar(256)")]
		public string ServiceName
		{
			get
			{
				return this._ServiceName;
			}
			set
			{
				if ((this._ServiceName != value))
				{
					this.OnServiceNameChanging(value);
					this.SendPropertyChanging();
					this._ServiceName = value;
					this.SendPropertyChanged("ServiceName");
					this.OnServiceNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ServicePackVersion", DbType="NVarChar(256)")]
		public string ServicePackVersion
		{
			get
			{
				return this._ServicePackVersion;
			}
			set
			{
				if ((this._ServicePackVersion != value))
				{
					this.OnServicePackVersionChanging(value);
					this.SendPropertyChanging();
					this._ServicePackVersion = value;
					this.SendPropertyChanged("ServicePackVersion");
					this.OnServicePackVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TcpPort", DbType="NVarChar(256)")]
		public string TcpPort
		{
			get
			{
				return this._TcpPort;
			}
			set
			{
				if ((this._TcpPort != value))
				{
					this.OnTcpPortChanging(value);
					this.SendPropertyChanging();
					this._TcpPort = value;
					this.SendPropertyChanged("TcpPort");
					this.OnTcpPortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ToolsPath", DbType="NVarChar(256)")]
		public string ToolsPath
		{
			get
			{
				return this._ToolsPath;
			}
			set
			{
				if ((this._ToolsPath != value))
				{
					this.OnToolsPathChanging(value);
					this.SendPropertyChanging();
					this._ToolsPath = value;
					this.SendPropertyChanged("ToolsPath");
					this.OnToolsPathChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="NVarChar(256)")]
		public string Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Version", DbType="NVarChar(256)")]
		public string Version
		{
			get
			{
				return this._Version;
			}
			set
			{
				if ((this._Version != value))
				{
					this.OnVersionChanging(value);
					this.SendPropertyChanging();
					this._Version = value;
					this.SendPropertyChanged("Version");
					this.OnVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VersionNr", DbType="NChar(10)")]
		public string VersionNr
		{
			get
			{
				return this._VersionNr;
			}
			set
			{
				if ((this._VersionNr != value))
				{
					this.OnVersionNrChanging(value);
					this.SendPropertyChanging();
					this._VersionNr = value;
					this.SendPropertyChanged("VersionNr");
					this.OnVersionNrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modified", DbType="Date")]
		public System.Nullable<System.DateTime> Modified
		{
			get
			{
				return this._Modified;
			}
			set
			{
				if ((this._Modified != value))
				{
					this.OnModifiedChanging(value);
					this.SendPropertyChanging();
					this._Modified = value;
					this.SendPropertyChanged("Modified");
					this.OnModifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Insterted", DbType="Date NOT NULL")]
		public System.DateTime Insterted
		{
			get
			{
				return this._Insterted;
			}
			set
			{
				if ((this._Insterted != value))
				{
					this.OnInstertedChanging(value);
					this.SendPropertyChanging();
					this._Insterted = value;
					this.SendPropertyChanged("Insterted");
					this.OnInstertedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsSCOM", DbType="Bit NOT NULL")]
		public bool IsSCOM
		{
			get
			{
				return this._IsSCOM;
			}
			set
			{
				if ((this._IsSCOM != value))
				{
					this.OnIsSCOMChanging(value);
					this.SendPropertyChanging();
					this._IsSCOM = value;
					this.SendPropertyChanged("IsSCOM");
					this.OnIsSCOMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotFoundSince", DbType="Date")]
		public System.Nullable<System.DateTime> NotFoundSince
		{
			get
			{
				return this._NotFoundSince;
			}
			set
			{
				if ((this._NotFoundSince != value))
				{
					this.OnNotFoundSinceChanging(value);
					this.SendPropertyChanging();
					this._NotFoundSince = value;
					this.SendPropertyChanged("NotFoundSince");
					this.OnNotFoundSinceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotFoundSinceDay", AutoSync=AutoSync.Always, DbType="Int", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public System.Nullable<int> NotFoundSinceDay
		{
			get
			{
				return this._NotFoundSinceDay;
			}
			set
			{
				if ((this._NotFoundSinceDay != value))
				{
					this.OnNotFoundSinceDayChanging(value);
					this.SendPropertyChanging();
					this._NotFoundSinceDay = value;
					this.SendPropertyChanged("NotFoundSinceDay");
					this.OnNotFoundSinceDayChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.vDatabases")]
	public partial class vDatabases
	{
		
		private long _ID;
		
		private string _symbol;
		
		private System.Nullable<long> _ManagedEntityRowId;
		
		private System.Nullable<long> _TopLevelHostManagedEntityRowId;
		
		private string _Path;
		
		private string _DisplayName;
		
		private System.Nullable<long> _ManagedEntityTypeRowId;
		
		private string _Collation;
		
		private string _DatabaseAutogrow;
		
		private string _DatabaseName;
		
		private string _LogAutogrow;
		
		private string _Owner;
		
		private string _RecoveryModel;
		
		private string _Updateability;
		
		private string _UserAccess;
		
		private System.Nullable<System.DateTime> _NotFoundSince;
		
		private System.Nullable<int> _NotFoundSinceDays;
		
		private System.Nullable<System.DateTime> _Modified;
		
		private string _PrincipalName;
		
		private string _InstanceName;
		
		public vDatabases()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="BigInt NOT NULL")]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_symbol", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
		public string symbol
		{
			get
			{
				return this._symbol;
			}
			set
			{
				if ((this._symbol != value))
				{
					this._symbol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManagedEntityRowId", DbType="BigInt")]
		public System.Nullable<long> ManagedEntityRowId
		{
			get
			{
				return this._ManagedEntityRowId;
			}
			set
			{
				if ((this._ManagedEntityRowId != value))
				{
					this._ManagedEntityRowId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TopLevelHostManagedEntityRowId", DbType="BigInt")]
		public System.Nullable<long> TopLevelHostManagedEntityRowId
		{
			get
			{
				return this._TopLevelHostManagedEntityRowId;
			}
			set
			{
				if ((this._TopLevelHostManagedEntityRowId != value))
				{
					this._TopLevelHostManagedEntityRowId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Path", DbType="NVarChar(255)")]
		public string Path
		{
			get
			{
				return this._Path;
			}
			set
			{
				if ((this._Path != value))
				{
					this._Path = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DisplayName", DbType="NVarChar(255)")]
		public string DisplayName
		{
			get
			{
				return this._DisplayName;
			}
			set
			{
				if ((this._DisplayName != value))
				{
					this._DisplayName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ManagedEntityTypeRowId", DbType="BigInt")]
		public System.Nullable<long> ManagedEntityTypeRowId
		{
			get
			{
				return this._ManagedEntityTypeRowId;
			}
			set
			{
				if ((this._ManagedEntityTypeRowId != value))
				{
					this._ManagedEntityTypeRowId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Collation", DbType="NVarChar(255)")]
		public string Collation
		{
			get
			{
				return this._Collation;
			}
			set
			{
				if ((this._Collation != value))
				{
					this._Collation = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatabaseAutogrow", DbType="NVarChar(255)")]
		public string DatabaseAutogrow
		{
			get
			{
				return this._DatabaseAutogrow;
			}
			set
			{
				if ((this._DatabaseAutogrow != value))
				{
					this._DatabaseAutogrow = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DatabaseName", DbType="NVarChar(255)")]
		public string DatabaseName
		{
			get
			{
				return this._DatabaseName;
			}
			set
			{
				if ((this._DatabaseName != value))
				{
					this._DatabaseName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogAutogrow", DbType="NVarChar(255)")]
		public string LogAutogrow
		{
			get
			{
				return this._LogAutogrow;
			}
			set
			{
				if ((this._LogAutogrow != value))
				{
					this._LogAutogrow = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Owner", DbType="NVarChar(255)")]
		public string Owner
		{
			get
			{
				return this._Owner;
			}
			set
			{
				if ((this._Owner != value))
				{
					this._Owner = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecoveryModel", DbType="NVarChar(255)")]
		public string RecoveryModel
		{
			get
			{
				return this._RecoveryModel;
			}
			set
			{
				if ((this._RecoveryModel != value))
				{
					this._RecoveryModel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Updateability", DbType="NVarChar(255)")]
		public string Updateability
		{
			get
			{
				return this._Updateability;
			}
			set
			{
				if ((this._Updateability != value))
				{
					this._Updateability = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserAccess", DbType="NVarChar(255)")]
		public string UserAccess
		{
			get
			{
				return this._UserAccess;
			}
			set
			{
				if ((this._UserAccess != value))
				{
					this._UserAccess = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotFoundSince", DbType="Date")]
		public System.Nullable<System.DateTime> NotFoundSince
		{
			get
			{
				return this._NotFoundSince;
			}
			set
			{
				if ((this._NotFoundSince != value))
				{
					this._NotFoundSince = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NotFoundSinceDays", DbType="Int")]
		public System.Nullable<int> NotFoundSinceDays
		{
			get
			{
				return this._NotFoundSinceDays;
			}
			set
			{
				if ((this._NotFoundSinceDays != value))
				{
					this._NotFoundSinceDays = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modified", DbType="Date")]
		public System.Nullable<System.DateTime> Modified
		{
			get
			{
				return this._Modified;
			}
			set
			{
				if ((this._Modified != value))
				{
					this._Modified = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrincipalName", DbType="NVarChar(256)")]
		public string PrincipalName
		{
			get
			{
				return this._PrincipalName;
			}
			set
			{
				if ((this._PrincipalName != value))
				{
					this._PrincipalName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InstanceName", DbType="NVarChar(256)")]
		public string InstanceName
		{
			get
			{
				return this._InstanceName;
			}
			set
			{
				if ((this._InstanceName != value))
				{
					this._InstanceName = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
